apiVersion: v1
kind: Secret
metadata:
  name: movie-secrets
  namespace: movie-app
type: Opaque
stringData:
  SECRET_KEY: "change-this-to-a-random-secret-key-in-production"
  DB_PASSWORD: "moviepass"
